package com.mycompany.app.entities;

import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import jakarta.persistence.GenerationType;

/**
 * Represents a category entity that can be associated with multiple fields.
 * This class is part of a many-to-many relationship with the Field entity.
 * 
 * Each Category has a unique identifier, a name, and a set of associated fields.
 * The relationship is managed through the `fields` collection in the Field entity.
 * 
 * Example usage:
 * <pre>
 * Category category = new Category();
 * category.setName("Science");
 * Set<Field> fields = new HashSet<>();
 * fields.add(new Field("Physics"));
 * category.setFields(fields);
 * </pre>
 * 
 * This class is annotated with JPA annotations to define the entity and its relationships.
 * The `@Entity` annotation marks it as a JPA entity, and the `@Table` annotation specifies the table name in the database.
 * The `@ManyToMany` annotation defines the many-to-many relationship with the Field entity.
 * The `@GeneratedValue` annotation indicates that the category ID will be generated automatically.
 * 
 * This class is typically used in applications that require categorization of fields, such as in a survey or form management system.
 * 
 * @see Field
 * @see jakarta.persistence.Entity
 * @see jakarta.persistence.Table
 * @see jakarta.persistence.ManyToMany
 * @see jakarta.persistence.GeneratedValue
 * @see jakarta.persistence.GenerationType
 * @see jakarta.persistence.Column
 * @see jakarta.persistence.Id
 * @see java.util.Set
 */
@Entity
@Table(name = "category")
public class Category {

  // Unique identifier for the category
  // This field is automatically generated by the database
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "category_id")
  private int id;

  // Name of the category
  // This field is mapped to the "category_name" column in the database
  @Column(name = "category_name")
  private String name;

  // Set of fields associated with this category
  // This establishes a many-to-many relationship with the Field entity
  // The relationship is managed by the Field entity's `categories` collection
  // The `mappedBy` attribute indicates that the relationship is managed by the Field entity
  // This means that the join table is defined in the Field entity, not here
  // The `fields` collection will contain all Field entities that are associated with this Category
  @ManyToMany(mappedBy = "categories")
  private Set<Field> fields;

  public int getId() {
    return id;
  } 

  public void setId(int id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Set<Field> getFields() {
    return fields;
  }

  public void setFields(Set<Field> fields) {
    this.fields = fields;
  }
}
