package com.mycompany.app.entities;

import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.JoinColumn;

/**
 * Represents a field entity that can be associated with multiple categories.
 * This class is part of a many-to-many relationship with the Category entity.
 * 
 * Each Field has a unique identifier, a name, and a set of associated
 * categories.
 * The relationship is managed through a join table named "field_category".
 * 
 * Example usage:
 * 
 * <pre>
 * Field field = new Field();
 * field.setName("Science");
 * Set<Category> categories = new HashSet<>();
 * categories.add(new Category("Physics"));
 * field.setCategories(categories);
 * </pre>
 * 
 * This class is annotated with JPA annotations to define the entity and its
 * relationships.
 * The `@Entity` annotation marks it as a JPA entity, and the `@Table`
 * annotation specifies the table name in the database.
 * The `@ManyToMany` annotation defines the many-to-many relationship with the
 * Category entity,
 * and the `@JoinTable` annotation specifies the join table and the join
 * columns.
 * The `@GeneratedValue` annotation indicates that the field ID will be
 * generated automatically.
 * 
 * This class is typically used in applications that require categorization of
 * fields, such as in a survey or form management system.
 * 
 * @see Category
 * @see jakarta.persistence.Entity
 * @see jakarta.persistence.Table
 * @see jakarta.persistence.ManyToMany
 * @see jakarta.persistence.JoinTable
 * @see jakarta.persistence.JoinColumn
 * @see jakarta.persistence.GeneratedValue
 * @see jakarta.persistence.GenerationType
 * @see jakarta.persistence.Column
 * @see jakarta.persistence.Id
 * @see jakarta.persistence.CascadeType
 * @see java.util.Set
 */
@Entity
@Table(name = "field")
public class Field {

  // Unique identifier for the field
  // This field is automatically generated by the database
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "field_id")
  private int id;

  // Name of the field
  // This field is mapped to the "field_name" column in the database
  @Column(name = "field_name")
  private String name;

  // Set of categories associated with this field
  // This establishes a many-to-many relationship with the Category entity
  // The relationship is managed by the join table "field_category"
  // The `CascadeType.ALL` allows all operations (persist, merge, remove,
  // refresh, detach) to cascade to the associated categories
  @ManyToMany(cascade = CascadeType.ALL)
  @JoinTable(name = "field_category", joinColumns = @JoinColumn(name = "field_id"), inverseJoinColumns = @JoinColumn(name = "category_id"))
  private Set<Category> categories;

  public int getId() {
    return id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Set<Category> getCategories() {
    return categories;
  }

  public void setCategories(Set<Category> categories) {
    this.categories = categories;
  }
}
